# Copyright 2026 OpenSynergy Indonesia
# Copyright 2026 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
{
    "name": "School Extracurricular",
    "version": "14.0.1.6.0",
    "website": "https://simetri-sinergi.id",
    "author": "PT. Simetri Sinergi Indonesia, OpenSynergy Indonesia, "
    "Odoo Community Association (OCA)",
    "license": "AGPL-3",
    "installable": True,
    "application": True,
    "depends": [
        "ssi_school",
        "ssi_master_data_mixin",
        "ssi_transaction_confirm_mixin",
        "ssi_transaction_open_mixin",
        "ssi_transaction_done_mixin",
        "ssi_transaction_cancel_mixin",
        "ssi_customer_invoice",
        "ssi_product_line_account_mixin",
        "web_tour",
    ],
    "data": [
        "security/ir_module_category_data.xml",
        "security/res_groups/school_extracurricular_category.xml",
        "security/res_groups/school_extracurricular.xml",
        "security/res_groups/school_extracurricular_offering.xml",
        "security/res_groups/school_extracurricular_participant.xml",
        "security/res_groups/school_extracurricular_fee_analysis.xml",
        "security/ir_model_access/school_extracurricular_category.xml",
        "security/ir_model_access/school_extracurricular.xml",
        "security/ir_model_access/school_extracurricular_offering.xml",
        "security/ir_model_access/school_extracurricular_participant.xml",
        "security/ir_model_access/school_enrollment_payment_term_extra_detail.xml",
        "security/ir_model_access/school_extracurricular_participant_allocation.xml",
        "security/ir_model_access/school_extracurricular_payment_term.xml",
        "security/ir_model_access/school_extracurricular_payment_term_detail.xml",
        "security/ir_model_access/school_extracurricular_create_due_invoice.xml",
        "security/ir_model_access/school_extracurricular_fee_analysis.xml",
        "security/ir_rule/school_extracurricular_offering.xml",
        "security/ir_rule/school_extracurricular_participant.xml",
        "ir_sequence/school_extracurricular_offering.xml",
        "ir_sequence/school_extracurricular_participant.xml",
        "sequence_template/school_extracurricular_offering.xml",
        "sequence_template/school_extracurricular_participant.xml",
        "approval_template/school_extracurricular_offering.xml",
        "approval_template/school_extracurricular_participant.xml",
        "policy_template/school_extracurricular_offering.xml",
        "policy_template/school_extracurricular_participant.xml",
        "menu.xml",
        "views/school_extracurricular_category.xml",
        "views/school_extracurricular.xml",
        "views/school_extracurricular_offering.xml",
        "views/school_extracurricular_participant.xml",
        "views/school_enrollment_payment_term.xml",
        "views/school_extracurricular_fee_analysis.xml",
        "wizards/school_extracurricular_create_due_invoice.xml",
        "menu_create_due_invoice.xml",
        "views/assets.xml",
    ],
}
