# Copyright 2026 OpenSynergy Indonesia
# Copyright 2026 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

from odoo_yaml_test import YamlTransactionCase

from odoo.tests import tagged


@tagged("post_install", "-at_install")
class TestSchoolExtracurricularSessionOperatingUnit(
    YamlTransactionCase
):  # pylint: disable=too-few-public-methods
    """Cover Operating Unit handling on the extracurricular session.

    Includes propagation from the Offering (both a directly created
    session and one generated by the Generate Sessions wizard),
    propagation following a later change to the Offering's own
    Operating Unit, record rule visibility, and the rejection of a
    direct write to ``operating_unit_id``.
    """

    def test_school_extracurricular_session_operating_unit(self):
        """Run every Operating Unit scenario for the session model."""
        self.run_yaml_scenario(
            "test_data_school_extracurricular_session_operating_unit.yaml"
        )
